#!/usr/bin/env python3
"""Deterministic bookkeeping for a notes directory. No dependencies.

Usage:
    notes_tools.py index [--root PATH]   Rebuild index.md from frontmatter
    notes_tools.py check [--root PATH]   Report broken links/anchors, missing
                                         frontmatter, legacy keys, expired
                                         pages, orphan footnotes, stale index
    notes_tools.py viz [--root PATH]     Write viz.html — an interactive graph
                                         of pages and links (open in a browser;
                                         loads cytoscape + marked from CDN)

The vault is an OKF v0.2 bundle (see the notes README). Default root: ~/notes
"""

import argparse
import datetime
import json
import re
import sys
from pathlib import Path

OKF_VERSION = "0.2"
SKIP_FILES = {"index.md", "log.md", "todos.md"}
SKIP_DIRS = {"tools", "raw", ".git", ".obsidian"}
REQUIRED_FM = ["type", "description", "tags", "when-to-load"]
LEGACY_FM = {
    "scope": "drop it — the directory is the area",
    "topics": "rename to tags",
    "source": "rename to resource",
}

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)
HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$", re.M)
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)#\s]+\.md)?(#[^)\s]+)?\)")
FOOTNOTE_RE = re.compile(r"\[\^([^\]\s]+)\]")
SOURCES_BLOCK_RE = re.compile(r"^sources:\s*$(.*?)(?=^\S|\Z)", re.S | re.M)
SOURCE_ID_RE = re.compile(r"^\s*-?\s*id:\s*(\S+)", re.M)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def parse_frontmatter(text: str) -> dict:
    m = FM_RE.match(text)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        if line[:1].isspace() or line.startswith("-"):
            continue  # nested keys (e.g. sources entries) are not top-level fields
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip().lower()] = v.strip()
    return fm


PALETTE = [
    "#4e79a7", "#f28e2b", "#59a14f", "#e15759", "#b07aa1",
    "#76b7b2", "#edc948", "#ff9da7", "#9c755f", "#bab0ac",
]


def parse_tags(value: str) -> list:
    return [t.strip() for t in value.strip("[]").split(",") if t.strip()]


def page_title(text: str, fm: dict, path: Path) -> str:
    if fm.get("title"):
        return fm["title"]
    m = re.search(r"^#\s+(.+?)\s*$", text, re.M)
    return m.group(1) if m else path.stem


def note_files(root: Path):
    for p in sorted(root.rglob("*.md")):
        rel = p.relative_to(root)
        if p.name in SKIP_FILES and len(rel.parts) == 1:
            continue
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        yield p


def slugify(heading: str) -> str:
    s = heading.strip().lower()
    s = re.sub(r"[^\w\- ]", "", s)
    return s.replace(" ", "-")


def build_index(root: Path) -> int:
    groups: dict[str, list] = {}
    for p in note_files(root):
        rel = p.relative_to(root)
        area = rel.parts[0] if len(rel.parts) > 1 else "(root)"
        text = read(p)
        fm = parse_frontmatter(text)
        groups.setdefault(area, []).append(
            (
                page_title(text, fm, p),
                rel.as_posix(),
                fm.get("description", ""),
                fm.get("when-to-load", ""),
            )
        )

    lines = [
        "---",
        f'okf_version: "{OKF_VERSION}"',
        "---",
        "",
        "# Index",
        "",
        "_Generated by `tools/notes_tools.py index` — do not edit by hand._",
        "",
    ]
    for area in sorted(groups):
        lines.append(f"## {area}")
        lines.append("")
        for title, rel, desc, when in groups[area]:
            entry = f"* [{title}]({rel})"
            if desc:
                entry += f" - {desc}"
            if when:
                entry += f" — **load when:** {when}"
            lines.append(entry)
        lines.append("")

    (root / "index.md").write_text("\n".join(lines), encoding="utf-8")
    n = sum(len(v) for v in groups.values())
    print(f"index.md rebuilt: {n} pages across {len(groups)} areas")
    return 0


def check(root: Path) -> int:
    problems = 0
    pages = list(note_files(root))
    todos = root / "todos.md"
    all_files = pages + ([todos] if todos.exists() else [])

    headings: dict[Path, set] = {}
    texts: dict[Path, str] = {}
    for p in all_files:
        texts[p] = read(p)
        headings[p.resolve()] = {slugify(h) for h in HEADING_RE.findall(texts[p])}

    for p in all_files:
        rel = p.relative_to(root)
        text = texts[p]

        # frontmatter (notes pages only)
        if p in pages:
            fm = parse_frontmatter(text)
            missing = [k for k in REQUIRED_FM if not fm.get(k)]
            if missing:
                print(f"FRONTMATTER  {rel}: missing {', '.join(missing)}")
                problems += 1
            for key, hint in LEGACY_FM.items():
                if key in fm:
                    print(f"LEGACY KEY   {rel}: {key} — {hint}")
                    problems += 1
            stale = fm.get("stale_after")
            if stale:
                try:
                    if datetime.date.today() >= datetime.date.fromisoformat(stale):
                        print(f"STALE        {rel}: stale_after {stale} has passed")
                        problems += 1
                except ValueError:
                    print(f"BAD DATE     {rel}: stale_after {stale!r} is not YYYY-MM-DD")
                    problems += 1

            # footnote citations must resolve to a sources[].id
            fm_match = FM_RE.match(text)
            body = text[fm_match.end():] if fm_match else text
            fn_ids = set(FOOTNOTE_RE.findall(body))
            if fn_ids:
                block = SOURCES_BLOCK_RE.search(fm_match.group(1)) if fm_match else None
                source_ids = set(SOURCE_ID_RE.findall(block.group(1))) if block else set()
                for fid in sorted(fn_ids - source_ids):
                    print(f"FOOTNOTE     {rel}: [^{fid}] has no matching sources id")
                    problems += 1

        # internal links and anchors
        for m in LINK_RE.finditer(text):
            target, anchor = m.group(1), m.group(2)
            if target and target.startswith(("http://", "https://")):
                continue
            if target:
                tpath = (p.parent / target).resolve()
                if not tpath.exists():
                    print(f"BROKEN LINK  {rel}: {target}")
                    problems += 1
                elif anchor:
                    if tpath not in headings:
                        headings[tpath] = {slugify(h) for h in HEADING_RE.findall(read(tpath))}
                    if slugify(anchor[1:]) not in headings[tpath]:
                        print(f"BROKEN ANCHOR {rel}: {target}{anchor}")
                        problems += 1
            elif anchor:
                if slugify(anchor[1:]) not in headings.get(p.resolve(), set()):
                    print(f"BROKEN ANCHOR {rel}: {anchor} (same file)")
                    problems += 1

    # todos.md is a non-reserved file, so OKF requires a type
    if todos.exists() and not parse_frontmatter(texts[todos]).get("type"):
        print("FRONTMATTER  todos.md: missing type (add `type: todo-list`)")
        problems += 1

    # index freshness
    index = root / "index.md"
    if not index.exists():
        print("INDEX  missing — run `notes_tools.py index`")
        problems += 1
    elif pages:
        newest = max(p.stat().st_mtime for p in pages)
        if index.stat().st_mtime < newest:
            print("INDEX  stale — a note is newer than index.md; rebuild it")
            problems += 1

    print(f"\n{problems} problem(s) found" if problems else "all checks passed")
    return 1 if problems else 0


def build_viz(root: Path) -> int:
    pages = list(note_files(root))
    ids = {p.resolve(): p.relative_to(root).as_posix() for p in pages}
    areas = sorted(
        {rel.split("/")[0] if "/" in rel else "(root)" for rel in ids.values()}
    )
    colors = {area: PALETTE[i % len(PALETTE)] for i, area in enumerate(areas)}

    nodes, edges, bodies, seen = [], [], {}, set()
    for p in pages:
        text = read(p)
        fm = parse_frontmatter(text)
        rel = ids[p.resolve()]
        area = rel.split("/")[0] if "/" in rel else "(root)"
        bodies[rel] = text
        nodes.append(
            {
                "data": {
                    "id": rel,
                    "label": page_title(text, fm, p),
                    "area": area,
                    "color": colors[area],
                    "size": 30 + min(60, len(text) // 200),
                    "tags": parse_tags(fm.get("tags", "")),
                    "description": fm.get("description", ""),
                    "when": fm.get("when-to-load", ""),
                    "status": fm.get("status", ""),
                }
            }
        )
        for m in LINK_RE.finditer(text):
            target = m.group(1)
            if not target or target.startswith(("http://", "https://")):
                continue
            tid = ids.get((p.parent / target).resolve())
            if tid and tid != rel and (rel, tid) not in seen:
                seen.add((rel, tid))
                edges.append({"data": {"id": f"{rel}->{tid}", "source": rel, "target": tid}})

    bundle = {
        "name": root.name,
        "areas": areas,
        "colors": colors,
        "nodes": nodes,
        "edges": edges,
        "bodies": bodies,
    }
    html = VIZ_TEMPLATE.replace("__TITLE__", root.name).replace(
        "__DATA__", json.dumps(bundle).replace("</", "<\\/")
    )
    out = root / "viz.html"
    out.write_text(html, encoding="utf-8")
    print(f"viz.html written: {len(nodes)} pages, {len(edges)} links, {out.stat().st_size} bytes")
    return 0


VIZ_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__ — notes graph</title>
<script src="https://cdn.jsdelivr.net/npm/cytoscape@3.30.2/dist/cytoscape.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked@12.0.2/marked.min.js"></script>
<style>
  * { box-sizing: border-box; margin: 0; }
  body { font: 14px/1.5 system-ui, sans-serif; color: #222; height: 100vh;
         display: flex; flex-direction: column; overflow: hidden; }
  header { display: flex; gap: 10px; align-items: center; padding: 8px 14px;
           border-bottom: 1px solid #ddd; background: #fafafa; flex-wrap: wrap; }
  header h1 { font-size: 15px; margin-right: 8px; }
  header input, header select { padding: 5px 8px; border: 1px solid #ccc;
           border-radius: 5px; font-size: 13px; }
  header input { width: 220px; }
  #legend { display: flex; gap: 10px; margin-left: auto; flex-wrap: wrap; font-size: 12px; }
  #legend span { display: inline-flex; align-items: center; gap: 4px; }
  #legend i { width: 10px; height: 10px; border-radius: 50%; display: inline-block; }
  #wrap { flex: 1; display: flex; min-height: 0; }
  #cy { flex: 1; }
  #sidebar { width: 0; overflow: hidden; transition: width .15s ease;
             border-left: 1px solid #ddd; background: #fff; }
  #sidebar.open { width: 440px; overflow-y: auto; }
  #sidebar .inner { padding: 16px 18px; }
  #meta { font-size: 12px; color: #555; border-bottom: 1px solid #eee;
          padding-bottom: 10px; margin-bottom: 12px; }
  #meta .path { font-family: monospace; }
  #doc h1 { font-size: 20px; margin: 10px 0 8px; }
  #doc h2 { font-size: 16px; margin: 14px 0 6px; }
  #doc h3 { font-size: 14px; margin: 12px 0 4px; }
  #doc p, #doc ul, #doc ol { margin: 6px 0; }
  #doc ul, #doc ol { padding-left: 22px; }
  #doc pre { background: #f5f5f5; padding: 8px 10px; border-radius: 5px;
             overflow-x: auto; font-size: 12px; margin: 8px 0; }
  #doc code { background: #f5f5f5; padding: 1px 4px; border-radius: 3px; font-size: 12px; }
  #doc blockquote { border-left: 3px solid #ddd; padding-left: 10px; color: #555; }
  #doc a { color: #2a6fb0; }
  #doc hr { border: 0; border-top: 1px solid #eee; margin: 12px 0; }
</style>
</head>
<body>
<header>
  <h1>__TITLE__</h1>
  <input id="search" type="search" placeholder="Search title, path, tags…">
  <select id="area"><option value="">all areas</option></select>
  <div id="legend"></div>
</header>
<div id="wrap">
  <div id="cy"></div>
  <div id="sidebar"><div class="inner">
    <div id="meta"></div>
    <div id="doc"></div>
  </div></div>
</div>
<script>
const bundle = __DATA__;

const areaSel = document.getElementById("area");
for (const a of bundle.areas) {
  const o = document.createElement("option");
  o.value = o.textContent = a;
  areaSel.appendChild(o);
}
const legend = document.getElementById("legend");
for (const a of bundle.areas) {
  const s = document.createElement("span");
  const i = document.createElement("i");
  i.style.background = bundle.colors[a];
  s.appendChild(i);
  s.appendChild(document.createTextNode(a));
  legend.appendChild(s);
}

const cy = cytoscape({
  container: document.getElementById("cy"),
  elements: [...bundle.nodes, ...bundle.edges],
  layout: { name: "cose", animate: false, padding: 30 },
  style: [
    { selector: "node", style: {
        "background-color": "data(color)", label: "data(label)",
        width: "data(size)", height: "data(size)", "font-size": 11,
        color: "#333", "text-valign": "bottom", "text-margin-y": 6,
        "text-wrap": "wrap", "text-max-width": 100 } },
    { selector: "edge", style: {
        width: 1.5, "line-color": "#bbb", "curve-style": "bezier",
        "target-arrow-shape": "triangle", "target-arrow-color": "#bbb",
        "arrow-scale": 0.8 } },
    { selector: ".dim", style: { opacity: 0.15 } },
    { selector: "node:selected", style: { "border-width": 3, "border-color": "#222" } }
  ]
});

function applyFilters() {
  const q = document.getElementById("search").value.trim().toLowerCase();
  const area = areaSel.value;
  cy.elements().removeClass("dim");
  if (!q && !area) return;
  const keep = cy.nodes().filter(n => {
    const d = n.data();
    const hay = (d.label + " " + d.id + " " + (d.tags || []).join(" ")).toLowerCase();
    return (!q || hay.includes(q)) && (!area || d.area === area);
  });
  cy.nodes().not(keep).addClass("dim");
  cy.edges().filter(e => e.source().hasClass("dim") || e.target().hasClass("dim"))
    .addClass("dim");
}
document.getElementById("search").addEventListener("input", applyFilters);
areaSel.addEventListener("change", applyFilters);

function resolvePath(base, href) {
  const parts = base.split("/").slice(0, -1).concat(href.split("/"));
  const out = [];
  for (const part of parts) {
    if (part === "." || part === "") continue;
    if (part === "..") out.pop(); else out.push(part);
  }
  return out.join("/");
}

function esc(s) {
  return s.replace(/[&<>"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
}

function showDetail(id) {
  const d = cy.getElementById(id).data();
  let meta = '<div class="path">' + esc(id) + "</div>";
  if (d.description) meta += "<div>" + esc(d.description) + "</div>";
  if (d.when) meta += "<div><b>load when:</b> " + esc(d.when) + "</div>";
  if (d.tags && d.tags.length) meta += "<div><b>tags:</b> " + esc(d.tags.join(", ")) + "</div>";
  if (d.status) meta += "<div><b>status:</b> " + esc(d.status) + "</div>";
  document.getElementById("meta").innerHTML = meta;

  const body = (bundle.bodies[id] || "").replace(/^---[\\s\\S]*?\\n---\\s*\\n/, "");
  const doc = document.getElementById("doc");
  doc.innerHTML = marked.parse(body, { gfm: true });
  doc.querySelectorAll("a").forEach(a => {
    const href = a.getAttribute("href") || "";
    if (/^https?:/.test(href)) { a.target = "_blank"; return; }
    const clean = href.split("#")[0];
    if (!clean.endsWith(".md")) return;
    const target = resolvePath(id, clean);
    if (bundle.bodies[target] !== undefined) {
      a.href = "#";
      a.addEventListener("click", ev => { ev.preventDefault(); selectNode(target); });
    }
  });
  document.getElementById("sidebar").classList.add("open");
}

function selectNode(id) {
  cy.$(":selected").unselect();
  const n = cy.getElementById(id);
  n.select();
  cy.animate({ center: { eles: n }, duration: 200 });
  showDetail(id);
}

cy.on("tap", "node", evt => showDetail(evt.target.id()));
cy.on("tap", evt => {
  if (evt.target === cy) {
    document.getElementById("sidebar").classList.remove("open");
    cy.$(":selected").unselect();
  }
});
</script>
</body>
</html>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("command", choices=["index", "check", "viz"])
    ap.add_argument("--root", default="~/notes")
    args = ap.parse_args()
    root = Path(args.root).expanduser().resolve()
    if not root.is_dir():
        print(f"notes root not found: {root}", file=sys.stderr)
        return 2
    if args.command == "index":
        return build_index(root)
    if args.command == "viz":
        return build_viz(root)
    return check(root)


if __name__ == "__main__":
    sys.exit(main())
