#!/usr/bin/env python3
"""Deterministic bookkeeping for a notes directory. No dependencies.

Usage:
    notes_tools.py index [--root PATH]   Rebuild index.md from frontmatter
    notes_tools.py check [--root PATH]   Report broken links/anchors, missing
                                         frontmatter, stale index

Default root: ~/notes
"""

import argparse
import re
import sys
from pathlib import Path

SKIP_FILES = {"index.md", "todos.md"}
SKIP_DIRS = {"tools", "raw", ".git", ".obsidian"}
REQUIRED_FM = ["type", "scope", "topics", "when-to-load"]

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)
HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$", re.M)
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)#\s]+\.md)?(#[^)\s]+)?\)")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def parse_frontmatter(text: str) -> dict:
    m = FM_RE.match(text)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip().lower()] = v.strip()
    return fm


def first_tldr_bullet(text: str) -> str:
    in_tldr = False
    for line in text.splitlines():
        if re.match(r"^#{1,3}\s*TL;DR", line, re.I):
            in_tldr = True
            continue
        if in_tldr:
            if line.startswith("#"):
                break
            stripped = line.strip()
            if stripped.startswith("-"):
                return stripped.lstrip("- ").strip()
    return ""


def note_files(root: Path):
    for p in sorted(root.rglob("*.md")):
        rel = p.relative_to(root)
        if p.name in SKIP_FILES and len(rel.parts) == 1:
            continue
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        yield p


def slugify(heading: str) -> str:
    s = heading.strip().lower()
    s = re.sub(r"[^\w\- ]", "", s)
    return s.replace(" ", "-")


def build_index(root: Path) -> int:
    groups: dict[str, list] = {}
    for p in note_files(root):
        rel = p.relative_to(root)
        area = rel.parts[0] if len(rel.parts) > 1 else "(root)"
        text = read(p)
        fm = parse_frontmatter(text)
        groups.setdefault(area, []).append(
            (rel.as_posix(), fm.get("when-to-load", ""), first_tldr_bullet(text))
        )

    lines = [
        "# Index",
        "",
        "_Generated by `tools/notes_tools.py index` — do not edit by hand._",
        "",
    ]
    for area in sorted(groups):
        lines.append(f"## {area}")
        lines.append("")
        for rel, when, tldr in groups[area]:
            entry = f"- [{rel}]({rel})"
            if when:
                entry += f" — **load when:** {when}"
            if tldr:
                entry += f" — {tldr}"
            lines.append(entry)
        lines.append("")

    (root / "index.md").write_text("\n".join(lines), encoding="utf-8")
    n = sum(len(v) for v in groups.values())
    print(f"index.md rebuilt: {n} pages across {len(groups)} areas")
    return 0


def check(root: Path) -> int:
    problems = 0
    pages = list(note_files(root))
    todos = root / "todos.md"
    all_files = pages + ([todos] if todos.exists() else [])

    headings: dict[Path, set] = {}
    texts: dict[Path, str] = {}
    for p in all_files:
        texts[p] = read(p)
        headings[p.resolve()] = {slugify(h) for h in HEADING_RE.findall(texts[p])}

    for p in all_files:
        rel = p.relative_to(root)
        text = texts[p]

        # frontmatter (notes pages only)
        if p in pages:
            fm = parse_frontmatter(text)
            missing = [k for k in REQUIRED_FM if not fm.get(k)]
            if missing:
                print(f"FRONTMATTER  {rel}: missing {', '.join(missing)}")
                problems += 1

        # internal links and anchors
        for m in LINK_RE.finditer(text):
            target, anchor = m.group(1), m.group(2)
            if target and target.startswith(("http://", "https://")):
                continue
            if target:
                tpath = (p.parent / target).resolve()
                if not tpath.exists():
                    print(f"BROKEN LINK  {rel}: {target}")
                    problems += 1
                elif anchor:
                    if tpath not in headings:
                        headings[tpath] = {slugify(h) for h in HEADING_RE.findall(read(tpath))}
                    if slugify(anchor[1:]) not in headings[tpath]:
                        print(f"BROKEN ANCHOR {rel}: {target}{anchor}")
                        problems += 1
            elif anchor:
                if slugify(anchor[1:]) not in headings.get(p.resolve(), set()):
                    print(f"BROKEN ANCHOR {rel}: {anchor} (same file)")
                    problems += 1

    # index freshness
    index = root / "index.md"
    if not index.exists():
        print("INDEX  missing — run `notes_tools.py index`")
        problems += 1
    elif pages:
        newest = max(p.stat().st_mtime for p in pages)
        if index.stat().st_mtime < newest:
            print("INDEX  stale — a note is newer than index.md; rebuild it")
            problems += 1

    print(f"\n{problems} problem(s) found" if problems else "all checks passed")
    return 1 if problems else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("command", choices=["index", "check"])
    ap.add_argument("--root", default="~/notes")
    args = ap.parse_args()
    root = Path(args.root).expanduser().resolve()
    if not root.is_dir():
        print(f"notes root not found: {root}", file=sys.stderr)
        return 2
    return build_index(root) if args.command == "index" else check(root)


if __name__ == "__main__":
    sys.exit(main())
